services:
  postgres:
    image: postgres:17
    container_name: news-portal-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_portal_db
    ports:
      - "5433:5432"
    volumes:
      - news_portal_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d news_portal_db"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  news_portal_pgdata:
    external: true
