-- Sync missing columns for "Setting" table to match current Prisma schema
-- This migration is intentionally additive (ADD COLUMN IF NOT EXISTS) to be safe across environments.

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "faviconUrl" TEXT;

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalContainerWidth" TEXT NOT NULL DEFAULT 'boxed';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalCustomContainerWidth" TEXT NOT NULL DEFAULT '1200';

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeWidgetTitleColor" TEXT NOT NULL DEFAULT '#1e293b';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeNewsTitleColor" TEXT NOT NULL DEFAULT '#111827';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeHoverColor" TEXT NOT NULL DEFAULT '#2563eb';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeExcerptColor" TEXT NOT NULL DEFAULT '#4b5563';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeMetaColor" TEXT NOT NULL DEFAULT '#9ca3af';

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postWidgetTitleColor" TEXT NOT NULL DEFAULT '#1e293b';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postContentColor" TEXT NOT NULL DEFAULT '#374151';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postLinkColor" TEXT NOT NULL DEFAULT '#2563eb';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postLinkHoverColor" TEXT NOT NULL DEFAULT '#1d4ed8';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postBadgeTextColor" TEXT NOT NULL DEFAULT '#374151';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postBadgeBgColor" TEXT NOT NULL DEFAULT '#f3f4f6';

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalPrimaryColor" TEXT NOT NULL DEFAULT '#2563eb';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalSecondaryColor" TEXT NOT NULL DEFAULT '#64748b';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalAccentColor" TEXT NOT NULL DEFAULT '#f59e0b';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalBackgroundColor" TEXT NOT NULL DEFAULT '#ffffff';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalBackgroundImage" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalBackgroundRepeat" TEXT NOT NULL DEFAULT 'no-repeat';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalBackgroundSize" TEXT NOT NULL DEFAULT 'cover';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalBackgroundPosition" TEXT NOT NULL DEFAULT 'center';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalBackgroundAttachment" TEXT NOT NULL DEFAULT 'scroll';

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postRelatedCount" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postRelatedPosition" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postRelatedPositions" TEXT NOT NULL DEFAULT '2';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedFilterType" TEXT NOT NULL DEFAULT 'category';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedDateRange" TEXT NOT NULL DEFAULT 'all';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedLayout" TEXT NOT NULL DEFAULT 'list';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedGridColumns" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedCardColumns" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedTitleFontSize" INTEGER NOT NULL DEFAULT 16;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedTitleFontWeight" TEXT NOT NULL DEFAULT '700';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedTitleLineHeight" TEXT NOT NULL DEFAULT '1.35';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedFontSize" INTEGER NOT NULL DEFAULT 14;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedBgColor" TEXT NOT NULL DEFAULT '#f9fafb';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedHeaderBgColor" TEXT NOT NULL DEFAULT '#f9fafb';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedTitleColor" TEXT NOT NULL DEFAULT '#1e293b';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedTextColor" TEXT NOT NULL DEFAULT '#1f2937';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineRelatedHoverColor" TEXT NOT NULL DEFAULT '#2563eb';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineAds" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postInlineAdPositions" TEXT NOT NULL DEFAULT '3';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postBottomRelated" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postAuthorBox" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postNavigation" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postRelatedFilterType" TEXT NOT NULL DEFAULT 'category';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postRelatedLayout" TEXT NOT NULL DEFAULT 'grid';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postRelatedLimit" INTEGER NOT NULL DEFAULT 3;

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "galleryLayout" TEXT NOT NULL DEFAULT 'slider';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "galleryEnableLightbox" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "galleryShowExif" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "galleryAutoPlay" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeWidgetTitleFontSize" TEXT NOT NULL DEFAULT '24px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeWidgetTitleFontWeight" TEXT NOT NULL DEFAULT '700';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeWidgetTitleFont" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeNewsTitleFontSize" TEXT NOT NULL DEFAULT '18px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeNewsTitleFontWeight" TEXT NOT NULL DEFAULT '600';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeNewsTitleFont" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeExcerptFontSize" TEXT NOT NULL DEFAULT '14px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeExcerptFontWeight" TEXT NOT NULL DEFAULT '400';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeExcerptFont" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeMetaFontSize" TEXT NOT NULL DEFAULT '12px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeMetaFontWeight" TEXT NOT NULL DEFAULT '500';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "homeMetaFont" TEXT NOT NULL DEFAULT 'Inter';

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postTitleFontWeight" TEXT NOT NULL DEFAULT '700';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postTitleFont" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postSubtitleFontSize" TEXT NOT NULL DEFAULT '18px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postSubtitleFontWeight" TEXT NOT NULL DEFAULT '500';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postSubtitleFont" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postContentFontSize" TEXT NOT NULL DEFAULT '18px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postContentFontWeight" TEXT NOT NULL DEFAULT '400';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postContentFont" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postWidgetTitleFontSize" TEXT NOT NULL DEFAULT '20px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postWidgetTitleFontWeight" TEXT NOT NULL DEFAULT '600';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "postWidgetTitleFont" TEXT NOT NULL DEFAULT 'Inter';

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "archiveTitleFontSize" TEXT NOT NULL DEFAULT '24px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "archiveTitleFontWeight" TEXT NOT NULL DEFAULT '700';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "archiveTitleFont" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "archiveExcerptFontSize" TEXT NOT NULL DEFAULT '14px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "archiveExcerptFontWeight" TEXT NOT NULL DEFAULT '400';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "archiveExcerptFont" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "archiveMetaFontSize" TEXT NOT NULL DEFAULT '12px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "archiveMetaFontWeight" TEXT NOT NULL DEFAULT '500';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "archiveMetaFont" TEXT NOT NULL DEFAULT 'Inter';

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalWidgetTitleFontSize" TEXT NOT NULL DEFAULT '20px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalWidgetTitleFontWeight" TEXT NOT NULL DEFAULT '600';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalWidgetTitleFont" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalNewsTitleFontSize" TEXT NOT NULL DEFAULT '18px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalNewsTitleFontWeight" TEXT NOT NULL DEFAULT '600';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalNewsTitleFont" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalMetaFontSize" TEXT NOT NULL DEFAULT '12px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalMetaFontWeight" TEXT NOT NULL DEFAULT '500';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalMetaFont" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalExcerptFontSize" TEXT NOT NULL DEFAULT '14px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalExcerptFontWeight" TEXT NOT NULL DEFAULT '400';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalExcerptFont" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalContentFontSize" TEXT NOT NULL DEFAULT '16px';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalContentFontWeight" TEXT NOT NULL DEFAULT '400';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "globalContentFont" TEXT NOT NULL DEFAULT 'Inter';

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "insertCodeHead" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "insertCodeBody" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "insertCodeFooter" TEXT;

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "notificationTelegramEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "notificationTelegramBotToken" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "notificationTelegramChatId" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "notificationEmailEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "notificationEmailFrom" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "notificationEmailTo" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "notificationSmtpHost" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "notificationSmtpPort" INTEGER;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "notificationSmtpUser" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "notificationSmtpPass" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "notificationSmtpSecure" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "notificationEvents" JSONB;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "printSettings" JSONB;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "aiOpenAiApiKeyEnc" TEXT;
