ALTER TABLE "Setting"
ADD COLUMN IF NOT EXISTS "postImageWatermarkUrl" TEXT,
ADD COLUMN IF NOT EXISTS "postImageWatermarkOpacity" INTEGER NOT NULL DEFAULT 35,
ADD COLUMN IF NOT EXISTS "postImageWatermarkSize" INTEGER NOT NULL DEFAULT 24,
ADD COLUMN IF NOT EXISTS "postImageWatermarkPosition" TEXT NOT NULL DEFAULT 'center',
ADD COLUMN IF NOT EXISTS "postImageWatermarkPaddingTop" INTEGER NOT NULL DEFAULT 24,
ADD COLUMN IF NOT EXISTS "postImageWatermarkPaddingRight" INTEGER NOT NULL DEFAULT 24,
ADD COLUMN IF NOT EXISTS "postImageWatermarkPaddingBottom" INTEGER NOT NULL DEFAULT 24,
ADD COLUMN IF NOT EXISTS "postImageWatermarkPaddingLeft" INTEGER NOT NULL DEFAULT 24;
